spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 661024
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  redis:
    #redis连接端口
    host: 127.0.0.1
    #redis 端口
    port: 6379
    jedis:
      pool:
        max-active: 5  #最大连接数
logging:
  level:
    root: warn
    cn.it.yip: info
  file: log/blog-pro.log
server:
  port: 80
comment.avatar: /images/boy.png
#静态资源对外暴露的访问路径
file.staticAccessPath: /api/file/**
#文件上传目录（注意Linux和Windows上的目录结构不同）
#file.uploadFolder=/root/uploadFiles/
file.uploadFolder: /www/server/blog/images
myblog.url: www.yipsoul.cn #上传图片时回显的路径

